### PR TITLE
Update for Xcode beta 5

### PR DESCRIPTION
**Pull request by barrault01**

### CODE REVIEW

**Comment by pietropizzi** [comment]
Hey thanks for the update. The first two files should not be part of the PR though. That is specific to your user. I will add some files to .gitignore and then you can rebase from that and we should be good.

**Comment by pietropizzi** [comment]
Ok I have gitignored and removed the whole `.swiftpm` folder.

**Comment by barrault01** [comment]
You are right I made the changes.

**Review by pietropizzi — APPROVED** [review]

**Comment by pietropizzi** [comment]
Also congrats on being the first other contributor! Thanks.

Released: https://github.com/pietropizzi/GridStack/releases/tag/0.2.4

**Pull request merged**
